[tool.ruff]
target-version = "py310"

lint.select = ["E", "F", "YTT", "W", "YTT", "ASYNC", "T10", "ISC", "G", "PIE", "RET", "INT", "RUF", "NPY", "PLE", "PLC", "PLW", "UP", "C4", "LOG", "ANN", "C4", "PGH", "SLF", "FA", "PERF", "A"]
lint.ignore = ["RET504", "PERF203", "ISC001", "ISC002", "ANN401", "ASYNC109"]
exclude = ["venv", "build", "dist"]
line-length = 88
fix = true

[tool.ruff.format]
quote-style = "double"  # Optional: "double" or "single"
indent-style = "space"  # Optional: "space" or "tab"
line-ending = "lf"  # Optional: "lf", "crlf", or "native"

[tool.mypy]
python_version = "3.10"
strict = true
ignore_missing_imports = true
exclude = ["venv", "build", "dist"]
show_column_numbers = true